# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81db20ae3b971c9bc9f34cfe2ca2167b4d624d1c265aae3f50be90f43fd84fcd782e6800ae94b30cbe03af3d51fdb9fac156701e8526be1ee39f72278c14c63b

test:
  secret_key_base: e109505e18b708917fda38ae6f717ee60fa6ee58fc7f0c4c248dce4c795b1d27eed316db45e92e1b76ab02594d46d9e2cf56241853d66a3ef4469d273920acd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
